CREATE TRIGGER [EMLEADDELETIONTRIGGER]
ON [LEAD]
FOR DELETE
AS

SET NOCOUNT ON /*Prevents an NHibernate error*/
DELETE FROM EMADDRESSBOOKMEMBER
	WHERE
		SLXLEADID IN (SELECT LEADID FROM DELETED) AND
		SLXMEMBERTYPE = 'Lead';		